baseURL = "https://mattwynne.github.io/explore-ddd-anti-authoritarian-team-practices-workshop/"
languageCode = "en-gb"
title = "Non-Authoritarian Team Practices"

[params]
  description = "A co-created handbook from Explore DDD 2026"
